
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medibook_app_development

 
test:
  <<: *default
  database: medibook_app_test


production:
  <<: *default
  database: medibook_app_production
  username: medibook_app
  password: <%= ENV['MEDIBOOK_APP_DATABASE_PASSWORD'] %>

mysql_development:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: password
  database: my_medibook_app
  db: localhost

mysql_production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: password
  database: my_medibook_app
  db: localhost

mysql_test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: password
  database: my_medibook_app
  db: localhost