default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password: password
  database: my_medibook_app
  db: localhost

development:
  <<: *default
  database: my_medibook_app

production:
  <<: *default
  database: my_medibook_app

test:
  <<: *default
  database: my_medibook_app
